### ISSUE TITLE
Filenames / Download folders / Users array

### ISSUE THREAD

**Issue by kraddock** [Karim-Arab/Tiktok2Youtube-shorts#3]
Hey Karim,

Nice job, it works great, however I find it would be better if videos are saved not with random timestamp filenames, but rather with the real video IDs, in separate folders (for example /@willSmith ). Some of the saved files are unreadable and it would be nice to know their IDs in order to re-download manually. Also, adding more than one user per run for better automation would be great (for example, an array of users - @user1, @user2, @user3, etc.

Thanks again!

**Comment by Karim-Arab** [comment]
Thanks for the suggestion, now videos are saved with its ID instead of timestamp or snaptik string, if you notice in names.txt in order as in the profile,
the multiple user's things are possible if you store all users in array and loop on them but that script was made for one specific thing one user videos

**Comment by Karim-Arab** [comment]
also folder path named as user id now
